### ISSUE TITLE
Le tooltip de l'icône d'équipe n'affiche pas tous les équipes?

### ISSUE THREAD

**Issue by maxeber** [Lan-Manager/lama#11]
De mon côté (en `localhost`) la liste des équipes ne s'affiche pas au complet et je sais pas pourquoi. Elle est bind sur `TournoiEnCours.LstEquipes` pourtant. Valide aussi avec les joueurs svp.

Quelqu'un peut valider que tout est beau pas en `localhost`?

**Comment by Tri125** [comment]
Peux tu élaborer? Quel tooltip?
